# Generated by Django 5.1.1 on 2024-09-14 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("text", models.TextField(unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerPerformance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_id", models.TextField(unique=True)),
                ("total_revenue", models.FloatField(default=0)),
                ("total_conversions", models.PositiveBigIntegerField(default=0)),
                ("conversion_rate", models.FloatField(db_index=True)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("text", models.TextField(unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("text", models.TextField(unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PerformanceDistribution",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("total_revenue", models.FloatField(default=0)),
                ("total_conversions", models.PositiveBigIntegerField(default=0)),
                ("count", models.PositiveIntegerField(default=0)),
                ("fk_category", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="orphex.category")),
                ("fk_status", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="orphex.status")),
                ("fk_type", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="orphex.type")),
            ],
            options={
                "unique_together": {("fk_status", "fk_type", "fk_category")},
            },
        ),
        migrations.CreateModel(
            name="CustomerPerformanceDistribution",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_id", models.TextField(unique=True)),
                ("total_revenue", models.FloatField(default=0)),
                ("total_conversions", models.PositiveBigIntegerField(default=0)),
                ("count", models.PositiveIntegerField(default=0)),
                ("fk_category", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="orphex.category")),
                ("fk_status", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="orphex.status")),
                ("fk_type", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="orphex.type")),
            ],
            options={
                "unique_together": {("customer_id", "fk_status", "fk_type", "fk_category")},
            },
        ),
    ]
