# Generated by Django 5.1.1 on 2024-09-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orphex", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="performancedistribution",
            index=models.Index(
                fields=["fk_type", "fk_category", "total_conversions", "total_revenue"], name="orphex_perf_fk_type_fccc1f_idx"
            ),
        ),
    ]
