# Generated by Django 5.1.1 on 2024-09-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orphex", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerConversionRate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_id", models.TextField(unique=True)),
                ("conversions", models.PositiveBigIntegerField()),
                ("revenues", models.FloatField()),
                ("rate", models.FloatField()),
            ],
        ),
    ]
