# Generated by Django 5.1.1 on 2024-09-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orphex", "0002_customerconversionrate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerconversionrate",
            name="rate",
            field=models.FloatField(db_index=True),
        ),
    ]
