# Generated by Django 5.1.1 on 2024-09-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orphex", "0003_alter_customerperformancedistribution_customer_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customerperformancedistribution",
            index=models.Index(
                fields=["fk_status", "fk_type", "fk_category", "customer_id", "total_conversions", "total_revenue"],
                name="orphex_cust_fk_stat_0eb57e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customerperformancedistribution",
            index=models.Index(
                fields=["fk_status", "fk_type", "customer_id", "total_conversions", "total_revenue"],
                name="orphex_cust_fk_stat_f1598d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customerperformancedistribution",
            index=models.Index(
                fields=["fk_status", "fk_category", "customer_id", "total_conversions", "total_revenue"],
                name="orphex_cust_fk_stat_ba3d3e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customerperformancedistribution",
            index=models.Index(
                fields=["fk_type", "fk_category", "customer_id", "total_conversions", "total_revenue"],
                name="orphex_cust_fk_type_b85dfc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customerperformancedistribution",
            index=models.Index(
                fields=["fk_status", "customer_id", "total_conversions", "total_revenue"], name="orphex_cust_fk_stat_349a55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerperformancedistribution",
            index=models.Index(
                fields=["fk_type", "customer_id", "total_conversions", "total_revenue"], name="orphex_cust_fk_type_65f303_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerperformancedistribution",
            index=models.Index(
                fields=["fk_category", "customer_id", "total_conversions", "total_revenue"],
                name="orphex_cust_fk_cate_b65451_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customerperformancedistribution",
            index=models.Index(
                fields=["customer_id", "total_conversions", "total_revenue"], name="orphex_cust_custome_e7ca15_idx"
            ),
        ),
    ]
