# Generated by Django 5.1.1 on 2024-09-14 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orphex", "0003_alter_customerconversionrate_rate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customerconversionrate",
            old_name="conversions",
            new_name="total_conversions",
        ),
        migrations.RenameField(
            model_name="customerconversionrate",
            old_name="revenues",
            new_name="total_revenue",
        ),
        migrations.CreateModel(
            name="StatusDistribution",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("conversions", models.PositiveBigIntegerField()),
                ("revenues", models.FloatField()),
                ("category_id", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="orphex.category")),
                ("status_id", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="orphex.status")),
                ("type_id", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="orphex.type")),
            ],
            options={
                "unique_together": {("status_id", "type_id", "category_id")},
            },
        ),
    ]
