# Generated by Django 5.1.1 on 2024-09-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orphex", "0004_rename_conversions_customerconversionrate_total_conversions_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="category",
            new_name="text",
        ),
        migrations.RenameField(
            model_name="status",
            old_name="status",
            new_name="text",
        ),
        migrations.RenameField(
            model_name="statusdistribution",
            old_name="conversions",
            new_name="total_conversions",
        ),
        migrations.RenameField(
            model_name="statusdistribution",
            old_name="revenues",
            new_name="total_revenue",
        ),
        migrations.RenameField(
            model_name="type",
            old_name="type",
            new_name="text",
        ),
    ]
